### ISSUE TITLE
adapting your Aleffull-NX theme for Recalbox

### ISSUE THREAD

**Issue by M-a-a-x** [fagnerpc/Alekfull-NX#2]
Hello

I'm M__a__a__x, beta tester of the Recalbox project. One of our users is in the process of adapting your Aleffull-NX theme for Recalbox.
Once finished we allow you to promote it on our forum, discord, twitch... of course always quote you?

Kind regards

M__a__a__x

-------------------------------------------------------------------------------------------------------------------

Bonjour,

Je me présente M__a__a__x béta testeur du projet Recalbox. Un de nos utilisateurs est en train d'adapter votre thème Alekfull-NX pour Recalbox.
Une fois terminé, nous autorisez-vous à en faire la promotion sur notre forum, discord, twitch…  bien entendu toujours en vous citant ?

Recalboxment votre,

M__a__a__x

**Comment by fagnerpc** [comment]
Hey [M-a-a-x](https://github.com/M-a-a-x),
Apologies for the delay.
Yes, you can adapt the theme for Recalbox.
I made a version of the theme for Recalbox also called Artflix NX - available here
https://github.com/fagnerpc/ARTFLIX-NX-Recalbox
Cheers
