### ISSUE TITLE
Request: Steam and Lightgun Games

### ISSUE THREAD

**Issue by Lazorne** [fagnerpc/Alekfull-NX#3]
Hello Batocera and others have enabled Steam support as a category.
I really love this theme and would love to have a image and background for Steam.
Another one I really miss is Lightgun Games.

Thanks!

**Comment by LordDarkneo** [comment]
+1 for the light gun, would really be appreciated ;)

**Comment by fagnerpc** [comment]
Hey [Lazorne](https://github.com/Lazorne) and [LordDarkneo](https://github.com/LordDarkneo),
Steam and Lightgun systems have already been added to the theme in the latest updates.

Thx for the feedback :)

**Comment by LordDarkneo** [comment]
TY @fagnerpc I'll give a try on the newest version then!
