### ISSUE TITLE
ADD new System Mega Duck

### ISSUE THREAD

**Issue by elcorsico** [fagnerpc/Alekfull-NX#4]
hi please a new system for you theme

system : Console , MEGA DUCK

check this : https://fr.wikipedia.org/wiki/Mega_Duck

ps: core are ok in retroarch

**Comment by fagnerpc** [comment]
Hey [elcorsico](https://github.com/elcorsico),
The Mega Duck system has already been added to the theme in the latest updates.

Thx for the feedback :)
