### ISSUE TITLE
Adapting Alekfull-NX to RetroPie and ES-DE

### ISSUE THREAD

**Issue by anthonycaccese** [fagnerpc/Alekfull-NX#6]
Hello!  I have started to port your awesome Alekfull-NX theme to be usable in the EmulationStation versions that are found in RetroPie and ES-DE.

You can find details of that port work here along with the changes I am making to make it work on those versions: https://github.com/anthonycaccese/alekfull-nx-retropie

I am writing to ask for your permission to share this port to users of RetroPie and ES-DE and also make sure that I have properly credited you and your original work.  

If you have any concerns I will of course stop my work immediately. 

Thank you again for your great work and design.  

Cheers

**Comment by fagnerpc** [comment]
Hey [anthonycaccese](https://github.com/anthonycaccese),
You're doing an amazing job porting the theme to Retropie and EmulationStation DE.
Yep, you have my permission... congratulations for the code in general (amazing readme.md too).
Thx

**Comment by anthonycaccese** [comment]
Thank you so much @fagnerpc
