### ISSUE TITLE
Automated Group - Lightgun - group icon and background image missing

### ISSUE THREAD

**Issue by MeCias** [fagnerpc/Alekfull-NX#7]
Hi
as the headline already stated, you can enable the lightgun group but the group icon and the background image are not getting displayed. Within the theme folder (batocera) I can see that the images are there.
A fix would be nice. Thanks in advanced

**Comment by fagnerpc** [comment]
Hey [MeCias](https://github.com/MeCias),
I fixed this issue in the last update.

Thanks for the feedback :)

**Comment by MeCias** [comment]
Thank you very much. Awesome work. :)
